name: Python package

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${% raw %}{{ matrix.python-version }}{% endraw %}
      uses: actions/setup-python@v2
      with:
        python-version: ${% raw %}{{ matrix.python-version }}{% endraw %}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
        python -m pip install --pre tox-gh-actions
    - name: Test with tox
      run: tox
